### ISSUE TITLE
windows != cmd

### ISSUE THREAD

**Issue by Naatan** [atomicgo/cursor#14]
This library seems to assume that Windows users by definition only use cmd.exe. It would be nice if one could instrument it in a way that doesn't make this assumption.

Case in point; git for windows ships with a bash for windows, which many developers tend to use.

**Comment by MarvinJWendt** [comment]
Hi, what makes you think that `cursor` assumes that you're using cmd?

**Comment by MarvinJWendt** [comment]
Yeah, windows handles it a bit different. That's why we have https://github.com/atomicgo/cursor/blob/main/cursor_windows.go
I tested it on several terminal on Windows (including VSC Terminal, Windows Terminal, CMD, PowerShell, etc.), without any bugs.

But I have to admit, I didn't test it with bash for windows. I'll consider upgrading the library, to detect which terminal is being used.

**Comment by Naatan** [comment]
It's not Windows that handles it differently, it's the shell (cmd). In theory your non-windows logic in cursor.go should work perfectly when using bash on windows. Thanks for considering this improvement!

**Comment by lammel** [comment]
> It's not Windows that handles it differently, it's the shell (cmd). In theory your non-windows logic in cursor.go should work perfectly when using bash on windows. Thanks for considering this improvement!

Quite a few issues were addressed with v0.2.0. I just testen on bash for windows (git bash) without any issue. Could you verify this works for you too @Naatan ?

**Comment by MarvinJWendt** [comment]
Closing this as stale.
